### ISSUE TITLE
support for binary installs

### ISSUE THREAD

**Issue by sbinet** [alisw/alibuild#294]
is it possible to have support for recipes where a complete build from sources is unnecessary, and just curl-ing a tarball (matching the correct arch/os, checking for some md5sum) is sufficient?

or is it completely out of `alibuild` scope?

**Comment by ktf** [comment]
Yes, that's a fundamental part of the design. Have a look at the remote store documentation. I will elaborate more when I am back from holidays.

**Comment by ktf** [comment]
I write here what I wrote on the mailing list. Let me know if this is enough for you to start.

First of all, yes, the remote store is a shared cache of already built packages. It currently supports two backends:

rsync
http (read-only)
local filesystem
and the logic is what you described:

--remote-store <some-url> will check the store for already built packages.
--remote-store <some-url>::rw will check the store for already built packages and push any package which was built locally to the store.
--remote-store <some-url> --write-store <some-other-url> will read packages from <some-url> but write them to <some-other-url>. This is useful for the case in which you want to mix backends (e.g. readonly http, write to local filesystem).
This comes very handy when you have a pool of machines doing the build or a lot
of users building exactly the same thing and it's the mechanism which allows
the daily builds to complete in 20 minutes rather than in hours as what was
built the day before is recycled or it allows us to pre-build the externals in
advance if they changed and only build AliRoot and AliPhysics after the 16:00
deadline.

Notice however that for a single user this is mostly an overkill, for the
following two reasons:

aliBuild already recycles builds which install in the same "sw" area.
If you use a remote store you cannot use system packages, because we cannot guarantee uniqueness of the configuration with an appreciable margin.
Devel packages and whatever depends on them will not go in the store (again, to guarantee uniqueness).
For these three reason, it seems a good tradeoff for the moment limiting the
central remote store to the build cluster only for the production architecture.

We have a few ideas on how to go that beyond a few central machines, but
clearly that takes time because of the obvious scalability issues and
it will most likely use CVMFS.

That said, if you are interested in setting up a remote store for a local
multi-machine / multi-user setup, you simply need to do:

alibuild build AliRoot --remote-store=$HOME/.alibuild/::rw
and that will create your store (locally, in this case), but again, if the goal
is to save autotools and gcc compilation, you are better off by installing them
as system tools (next version of alibuild / alidist due soon will hopefully
improve the number of system GCC we support).

**Comment by Barthelemy** [comment]
Hi, 

Very interesting read. One use case that you don't really mention is when people want to start coding and do not want to wait >2 hours for everything to build. I develop on several systems and for every one I have to rebuild everything from scratch. 

What could be cool is that alibuild detects what packages could be installed by the system and propose to do it instead of download/compiling them. 

Barth

**Comment by ktf** [comment]
If you update to aliBuild 1.3.0 (`pip install --upgrade alibuild`) you have a new version of `aliDoctor` which will tell you what it could and what it could not do. E.g.:

```
aliDoctor O2
```

also notice that `aliBuild --dry-run build O2` will also give you some insight.

**Comment by ktf** [comment]
I've updated the front page with a few aliBuild highlights, including binary packages, and I am closing this bug report. Please open a new issue if you think you need more detailed documentation to explain how it works.
