### ISSUE TITLE
Feature request: controlling functionality for alidist

### ISSUE THREAD

**Issue by matthiasrichter** [alisw/alibuild#334]
I wonder if it might be useful to add some functionality for controlling alidist. E.g. switching branches or tags in alidist, listing branches or tags according to a regexp search, printing the currently active branch/version.

The currently active branch/version could maybe also be included in the log output when aliBuild is starting.

**Comment by ktf** [comment]
I'd rather avoid wrapping git in aliBuild, as I am sure the git folks are much better then me in providing this kind of information.

The git hash is already provided in the debug output, we can make it more prominent. Do you agree we close this and we open a "Make git branch / hash available in non debug log" action item?

**Comment by matthiasrichter** [comment]
Sure, git provides all this. However, I was trying to find a better workflow. When I was playing around with different configurations, i.e. branches in alidist, I had to go into the directory 'alidist', then type whatever git command, then back. So I was thinking of a simpler way of doing that. Sure, can be discussed to which extent one wants to wrap git functionality.

Making the branch name more visible in the output would be the first step. I think, the hash is pure debug information for experts.

**Comment by ktf** [comment]
Back to this. We now actually have a couple of things in the pipeline which might improve this item.

The goal, rather than provide support for switching branches, is to minimise the number of branches needed (which is frankly getting complicated).

The first one is that the so called [defaults](http://alisw.github.io/alibuild/user.html#defaults) have been extended (in the `next` branch and in the soon to be tagged `1.4.0` release) with the ability to disable packages (e.g. you could have an `HLT` default which disables various generators), and to override package metadata (e.g. switch between ROOT 5 and ROOT 6). See for example alisw/alidist#498. This should remove the need to care for extra branches in 90% of the cases.

**Comment by matthiasrichter** [comment]
I close this issue as the concept of defaults has been introduced now. This makes handling of sets of recipes via branches obsolete, and thus the helper functionality.
