### ISSUE TITLE
Python3 and Python2 do not produce the same package hashes

### ISSUE THREAD

**Issue by ktf** [alisw/alibuild#378]

**Comment by ktf** [comment]
Most likely the problem is due to a non-stable topological sort.

**Comment by ktf** [comment]
@dberzano this is fixed, correct?

**Comment by dberzano** [comment]
Since aliBuild 1.5.0, build hashes are consistent for a given Python version. So, Python 2 hashes are different from Python 3 ones. The problem we had was that build hashes in Python 3 changed from one build to the next. It had nothing to do with the topological sort, but it depended on the way dictionaries are represented into strings (used to compute such hashes): Python 2 always yields items in the same order, Python 3 returns them in a different order at each call.

The problem was fixed by using OrderedDict instead of dict. (Closing.)
