### ISSUE TITLE
alienv shell looses bash completion

### ISSUE THREAD

**Issue by sawenzel** [alisw/alibuild#426]
As a user I'd like to have bash completion correctly working.
The shell opened by `alienv enter AliRoot/latest` looses such completion capabilities. This is in particular true for git.

I would be great not loosing the completion features in the alienv shell.

**Comment by ktf** [comment]
As stated in the documentation for alienv enter (`alienv --help`):

```
    enter [--shellrc] MODULE1[,MODULE2...]
      ...
      If you want to retain your shell startup files use --shellrc.
      Alternatively you can use the load command in the current shell.
```

you have to options: pass `--shellrc` which has the desired effect, or use `alienv load` which will load the environment in the current shell. The reason why this is not done by default is that historically it was that way to avoid environment pollution from the user `.bashrc`. Given I think a few things on the grid depend on this default behaviour, I think it's unlikely to change. Notice you can probably have an alias similar to:

```
alias alienter="alienv enter --shellrc"
```

to get a similar behaviour. Does this address your question?

**Comment by ktf** [comment]
@dberzano might have more comments.

**Comment by dberzano** [comment]
Hi @sawenzel, `--shellrc` is exactly what you need (if you type `alienv` with no options you'll see an online help).

This is _not_ the default option because... 90% of the users swear they don't have garbage in their `.bashrc`, but they do (including leftovers from custom/legacy/broken AliRoot installations). So, the default behaviour is what makes _our_ software always work.

Please close if you're satisfied!

**Comment by sawenzel** [comment]
Ok ... I made it work. Thanks for the help.

**Comment by sawenzel** [comment]
Actually, there is the drawback that then I don't see the nice prompt that you provide anymore. (The one that shows the current environment loaded).
