### ISSUE TITLE
build only the development package

### ISSUE THREAD

**Issue by Barthelemy** [alisw/alibuild#437]
As a user it can happen that I want to rebuild my development package but not the dependencies. Basically I want to keep my whole stack the same but what I am working on. 

At the moment if I use `alibuild build`, it often happens that it starts rebuilding large dependencies because their version was updated or their branch received a commit. Then I have to wait 30 minutes before resuming my work.

The addition of a flag --no-dependencies-rebuild would help. It would only compile the package that is specified on the command line (typically O2).

**Comment by ktf** [comment]
I think rather than doing this, we should just make sure no recipe uses a branch to build, at least by default. That would have the same effect and would not force you to specify an extra variable. Do you know what triggered the build?

**Comment by Barthelemy** [comment]
Are there some high level logs somewhere ? I find the logs for the specific packages only. I am not sure which one triggered it. 

I still think that you could end up with a dependency version bump in a time you would really not want it. Less probable if there are no branch to build but still possible with specific version over the large number of dependencies.

**Comment by dberzano** [comment]
Hi @Barthelemy, we'd like to favor convention over configuration in aliBuild - the only factors causing a rebuild is a change in the recipes, or the source code, so if the recipes do not get updated, no rebuild occurs.

* If you want to rebuild the package you want without involving aliBuild, you can, by going into the build directory and using `make` (or whatever)
* If you want to involve aliBuild because you want to test a new recipe, you can download only the file you want into your alidist directory and go on like this

What do you think?

**Comment by Barthelemy** [comment]
I agree and I think that this issue can be closed. Thank you !
