### ISSUE TITLE
RPATH relocation missing on Linux ?

### ISSUE THREAD

**Issue by dennisklein** [alisw/alibuild#534]
Hi, looks like we need the `RPATH` relocation we did for MacOS also on Linux:

```
$ chrpath -l sw/INSTALLROOT/4a62963eb847291e35e211a2049d5a0978980be6/fedora27_x86-64/FairMQ/dev-2/bin/bsampler      
sw/INSTALLROOT/4a62963eb847291e35e211a2049d5a0978980be6/fedora27_x86-64/FairMQ/dev-2/bin/bsampler: RPATH=/home/dklein/alfa/sw/INSTALLROOT/4a62963eb847291e35e211a2049d5a0978980be6/fedora27_x86-64/FairMQ/dev-2/lib64:/home/dklein/alfa/sw/fedora27_x86-64/FairLogger/v1.0.5-3/lib64/fairlogger:/home/dklein/alfa/sw/fedora27_x86-64/ZeroMQ/v4.2.2-2/lib:/home/dklein/alfa/sw/fedora27_x86-64/nanomsg/v1.1.2-2/lib:/home/dklein/alfa/sw/fedora27_x86-64/msgpack/cpp-2.1.5-7/lib
$ chrpath -l sw/fedora27_x86-64/FairMQ/latest/bin/bsampler
sw/fedora27_x86-64/FairMQ/latest/bin/bsampler: RPATH=/home/dklein/alfa/sw/INSTALLROOT/9b0a20612235c42d4f7a64d15d39793337bcfb4a/fedora27_x86-64/FairMQ/dev-1/lib64:/home/dklein/alfa/sw/fedora27_x86-64/FairLogger/v1.0.5-3/lib64/fairlogger:/home/dklein/alfa/sw/fedora27_x86-64/ZeroMQ/v4.2.2-2/lib:/home/dklein/alfa/sw/fedora27_x86-64/nanomsg/v1.1.2-2/lib:/home/dklein/alfa/sw/fedora27_x86-64/msgpack/cpp-2.1.5-7/lib
```

You can see that the relocated binary still has the unrelocated `RPATH` entry. My guess is, that this was masked so far, because most recipes generate modulefiles that prepend to `LD_LIBRARY_PATH` ...

As far as I can see, this also affects shared libraries:
```
$ chrpath -l sw/fedora27_x86-64/FairMQ/latest/lib64/libFairMQ.so
sw/fedora27_x86-64/FairMQ/latest/lib64/libFairMQ.so: RPATH=/home/dklein/alfa/sw/INSTALLROOT/9b0a20612235c42d4f7a64d15d39793337bcfb4a/fedora27_x86-64/FairMQ/dev-1/lib64:/home/dklein/alfa/sw/fedora27_x86-64/FairLogger/v1.0.5-3/lib64/fairlogger:/home/dklein/alfa/sw/fedora27_x86-64/ZeroMQ/v4.2.2-2/lib:/home/dklein/alfa/sw/fedora27_x86-64/nanomsg/v1.1.2-2/lib:/home/dklein/alfa/sw/fedora27_x86-64/msgpack/cpp-2.1.5-7/lib
```

Affects: Linux (Fedora 27), aliBuild 1.5.3.

**Comment by ktf** [comment]
I would not use rpath at all, frankly. My experience is that `LD_LIBRARY_PATH` is way more reliable and easier to use.

**Comment by dennisklein** [comment]
I disagree with your conclusion. `LD_LIBRARY_PATH` is not even recognized in all cases (see section _Secure-execution mode_ [man ld.so](http://man7.org/linux/man-pages/man8/ld.so.8.html)) - granted it is rather a minor impact for our environment, but it surely does not contribute to **more** reliability. Which aspect increases `LD_LIBRARY_PATH`'s reliability over `RPATH` in your opinion?

Easier to use for whom? The author of tooling such as package managers or the end user? Being able to just invoke an installed executable **without** having to first setup my shell environment is easier to use in my opinion. Also have a look at this writeup: http://xahlee.info/UnixResource_dir/_/ldpath.html

**Comment by dennisklein** [comment]
I did some more research and found a way to make the `RPATH` relative. Inside a given `RPATH` the keyword `$ORIGIN` is replaced with the directory the loading executable/library is located in at run time. This solves my use case.

Btw, I also found that the ELF `DT_RPATH` entry is deprecated and `DT_RUNPATH` is preferred. The difference is, that `DT_RPATH` has precedence over `LD_LIBRARY_PATH` while `DT_RUNPATH` has not. One can enable `DT_RUNPATH` with the linker option `--enable-new-dtags` (Chapter 41.10 [TLPI](http://man7.org/tlpi/)).

**Comment by ktf** [comment]
There are three main problems with RPATH:

- It's linker / OS dependent and relies on the fact there is enough padding for the relocation to happen. Sometimes you get mysterious errors simply because the padding was not enough and you end up cutting part of it. In general manipulating text files is a necessary evil, manipulating binary files is a greater evil and if it can be avoided it's better. 
- It's can be fixed only at install time, by the installer, and sometimes that might not be the right moment. I've seen CVMFS installations with a given rpath being used "by copy" to NFS in a different path. That does not work with RPATH while it's easy to adapt the `LD_LIBRARY_PATH` accordingly.
- If you need to debug things, you need to ask your user for details about every single loaded DSO, while with LD_LIBRARY_PATH the environment is sufficient.

Moreover, the lookup path for libraries is only one of the things you have in the environment, think for example about ROOTSYS, so you better have in any case something like environment modules. At that point, why introducing an extra degree of freedom with RPATH?

My personal experience is that RPATH works reliably only when the build and deployment system are the same, but that not quite the case for our software which gets distributed via cvmfs.

That said, if you have time to spare and you can fix the RPATH in a way that is also compatibile with the environment modules, I've no particular objections.

**Comment by dennisklein** [comment]
Well, I ended up using a relative `RUNPATH` entry which will not prevent any existing and future `LD_LIBRARY_PATH` wizardry to be performed ...and it solves my use case :)

In the context of our whole dependency tree I will still need `LD_LIBRARY_PATH` management, but I wanted to fix at least the small part I have some influence over, if there was a better way to do it. Let's see how it works out.

**Comment by ktf** [comment]
Sounds good.
