### ISSUE TITLE
cmake is unable to download by protocol HTTPS while own cmake option procedure

### ISSUE THREAD

**Issue by LuMoVo** [alisw/alibuild#545]
When I aply my cmake option

    cmake -DCMAKE_BUILD_TYPE=RELEASE \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DINSTALL_C_EXAMPLES=OFF \
    -DINSTALL_PYTHON_EXAMPLES=OFF \
    -DBUILD_EXAMPLES=OFF \
    -DOPENCV_EXTRA_MODULES_PATH=/home/luke/cv/last/opencv_contrib/modules  ..

it will cause faults (written in warnings) with downloading some necessary files by HTTPS protocol. 

    CMake Warning at cmake/OpenCVDownload.cmake:190 (message):
      IPPICV: Download failed: 1;"Unsupported protocol"
     
      For details please refer to the download log file:
     
      /home/luke/cv/last/oc/opencv/build/CMakeDownloadLog.txt

[Here][1] is full output- result of entered CMake command. An info from file :

      CMakeDownloadLog.txt
is also shown [here][2]. Seems like libcurl is not working. Ok I installed the last release of curl and also OpenSSL and I have make `./configure --with-ssl` comand. When I see configured [log of libcurl][3] there I can see HTTPS on enum of protocols. Soo **that should be supported**. But Cmake again while configuration and generating makes still that same fails with downloads written in that warnings ( shown above in my links ).  **CMake tells: not supported** or **disabled in libcurl** but **libcurl says** (it seems like..) **suported**. Ah. I am thinking about it but dont know what else is wrong.

Does anybody know what could be wrong or do you have any idea/tips please ??

  [1]: https://pastebin.com/CAWU6fdY
  [2]: https://pastebin.com/Rf6CAKQd
  [3]: https://pastebin.com/UBvRs8d0

**Comment by LuMoVo** [comment]
Well, thank you for your comment. But can you give me please some way how can I set CMake for use to libcurl ? I am trying to find some possibilities but till now, nothing is working yet.

**Comment by dennisklein** [comment]
You need to recompile CMake itself to change which libcurl is used. So, e.g.

1. Install libcurl with https support in your system
2. Download the CMake source
3. Bootstrap CMake, e.g. `./bootstrap --system-curl --prefix=/where/to/install` (find all options with `./bootstrap --help .`
4. `make`
5. `make install`

Consult the CMake docs for more information on how to compile and install CMake (you may find CMake also already pre-packaged for your operating system).

**Comment by dennisklein** [comment]
The `cmake` program itself has a dependency on libcurl to implement certain feature of CMake. Of course, any software project, that uses CMake as its build system, may also depend on libcurl. Do not confuse those two orthogonal things when searching CMake and libcurl topics on the web.

**Comment by LuMoVo** [comment]
Thank you for help with this. Unfortunelly. I have issue another issue with `./bootstrap` (also tried with added option paramaters)  I see one of printed rows is: `C++ compiler on this system is: g++  -std=gnu++1y` . It get couples of this 2 errors seen in [output](https://pastebin.com/VnFSRVu8). And another more info about failing with tests are in [cmake_bootstrap.log](https://pastebin.com/b2u3brYM) there sixth test failure to complete. Seems to compiling isn't with -std=c++11. I tried `sudo apt-get install --reinstall g++` and find something to make set default system generator on: `g++  -std=c++11` but I am not sucessful yet. If anyboy have some tips, i would be glad. Just have this problem with g++ it cannot compile correctly.

**Comment by dennisklein** [comment]
Which operating system distribution and version are you using (your logs suggest it is quite old because your g++ version appears to be 4.8?)? The oldest system I have successfully compiled CMake 3.11 on recently was Debian Jessie with g++ 4.9.2. From a quick online search it appears to me the oldest GCC supported by CMake is 4.9 (but I could be wrong). The flag `-std=gnu++1y` is unlikely to be the problem, because it is a superset of `-std=gnu++11`.

You could either downgrade your CMake significantly to a version in the low 3.x, e.g. 3.3 (This is a guess, but older versions are more likely to compile with g++ 4.8). Or you could try to upgrade your system to have at least g++ 4.9+. (C++11 support in g++ 4.8 was feature complete but still experimental).

Also, do not bootstrap and compile with sudo... Only `make install` needs to run as root and only, if you install into a prefix that is not writable by your user account.

**Comment by ktf** [comment]
Please, move the discussion somewhere else. This has nothing to do with aliBuild, the build tool of the ALICE experiment at CERN.
