### ISSUE TITLE
Version-dependent dependencies

### ISSUE THREAD

**Issue by qgp** [alisw/alibuild#65]
For some packages, the dependencies for different versions of the package change. It would be beneficial to have the possibility of specifying dependencies to be pulled in only for some versions.

In contrast to other issues, this is not really critical at the moment.

**Comment by ktf** [comment]
IMHO, this should be fixed by simply adjusting the recipe accordingly and doing a different commit. Having recipes that support "multiple version" is really not the way to go, IMHO, as those kind of changes should really be maintained properly in git. Closing this. Feel free to reopen if you have an actual use case which is not covered by / extremely impractical using the suggested workflow.
