### ISSUE TITLE
aliBuild does not correctly get my cern gitlabs credentials from the command line for FLUKA

### ISSUE THREAD

**Issue by davidrohr** [alisw/alibuild#681]
Running `aliBuild --defaults o2 build O2Suite --debug` on the EPN, it prompts me for my cern credentias to get fluka from gitlab.
Apparently it does a parallel checkout for FLUKA and FLUKA_VMC, which breaks the parsing of the credentials from the command line.
I think what happens is that it asks for my username twice in parallel, overwriting each other.
When I enter the username once, it prints to the console that it asks for the password.
But actually, the second username query is still ongoing. I.e. instead of the password, I have to enter the username again.
Doing so, it asks for the password a second time. So now I enter the password, and alibuild continues.
At some point it gets stuck, and this is because the second password querry still seems to run in the background.
So when I enter the password again, it continues.
This is quite confusing behavior, and it will probably prevent many users from building O2 currently.

**Comment by aphecetche** [comment]
Got caught by this as well and it's even worse, as I cut-and-paste my password from a password manager and so it gets used (and thus echoed in full to the terminal) as the username for the second request...

**Comment by aphecetche** [comment]
I'm actually unable to use it at all because now I have : 
```
Cloning into bare repository '/home/laurent/alice/sw/MIRROR/fluka'...
Cloning into bare repository '/home/laurent/alice/sw/MIRROR/fluka_vmc'...
Username for 'https://gitlab.cern.ch': Username for 'https://gitlab.cern.ch':
```
i.e. can't even enter the first username ...

**Comment by pzhristov** [comment]
You do not see correctly the output, but if you enter username/password twice it should work. Probably we need a fix to avoid multiple processes asking credentials.

**Comment by davidrohr** [comment]
OK, but entering the username twice, then the passwort twice, even though the console shows something different, is extremely confusing and certainly not something we want all our users to do I would say.

**Comment by pzhristov** [comment]
I agree - aliBuild should wait until the first interaction finishes and then ask again, without any "parallelisation".

**Comment by TimoWilken** [comment]
Here are some ideas of how to solve this. Do these options sound sensible? Any preference for either? (Cc: @ktf)

## 1. Use `ssh-askpass` to stop prompts from overlapping

Set `GIT_ASKPASS` to some `ssh-askpass`-compatible program. This would make git pop up one GUI window for each password request, which should be a lot less confusing than overlapping terminal prompts.

The issue here would be to detect askpass programs -- we'd need a list of common ones, and maybe even ship our own simple one with alibuild.

Downsides: assumes a graphical environment. Shouldn't be a problem in CI as we store the credentials properly there. This might break with stuff like `alidock` or otherwise running in a container, I'm not sure.

## 2. Prompt for passwords ourselves, and use `git credential-cache`

Before we start cloning the repos, we could do `GIT_TERMINAL_PROMPT=0 git ls-remote <source>'` for each one to test whether we can access it. If not, we could prompt for a username and password for the domain ourselves, pass it to `git-credential-cache` and use `git -c 'credential.helper=cache --timeout <something reasonable>'` for each subsequent git command.

(We should probably do `git credential-cache exit` when done cloning, so that subsequent commands/builds can't access these credentials.)

Downsides: won't work on slc6 because the git version is too old. Hopefully no users are still on slc6, though.

**Comment by ktf** [comment]
2. sounds the best actually
