### ISSUE TITLE
alibuild breaks O2 compilation in O2Version.cxx#L30

### ISSUE THREAD

**Issue by adriansev** [alisw/alibuild#740]
Hi! On my system when doing cd chained with other command i get this:
```
cd O2 && git rev-parse HEAD
/home/physics-tools/alicebuild/o2/O2
f05fcf3ee63077d484bf6d49907d9b78a0e0f88a
```
this breaks https://github.com/alisw/alibuild/blob/master/alibuild_helpers/build.py#L51
which will return a wrong hash, that when replaced within O2::O2Version.cxx will create
a line without termination nor continuation and compilation breaks.

I tried to modify the getDirectoryHash definition with:
```
 def getDirectoryHash(d):
-  err, out = getstatusoutput("cd %s && git rev-parse HEAD" % d)
+  try:
+    os.chdir(d)
+  except Exception:
+    print("Error changing directory to {d}")
+    return ''
+  err, out = getstatusoutput("git rev-parse HEAD")
   dieOnError(err, "Impossible to find reference for %s" % d)
   return out
```

but aliBuild stopped instantly with 
`ERROR: [Errno 2] No such file or directory: 'alidist/o2physics.sh'`
even if
```
ls -la alidist/o2physics.sh
-rw-rw-r-- 1 adrian adrian 1923 2022/Feb/02 18:25:20 alidist/o2physics.sh
```

Any idea how can this be solved? and why a seemingly good code (and i would say that is better
to use os.chdir) breaks anything else?
Thanks a lot!!

**Comment by TimoWilken** [comment]
Hi @adriansev!

That's very odd. Are you aliasing `cd` to `pushd` or something similar?

Could you try changing `getDirectoryHash` like so instead:

```patch
 def getDirectoryHash(d):
-  err, out = getstatusoutput("cd %s && git rev-parse HEAD" % d)
+  err, out = getstatusoutput("cd %s >/dev/null 2>/dev/null && git rev-parse HEAD" % d)
   dieOnError(err, "Impossible to find reference for %s" % d)
   return out
```

Which might be a good idea anyway, to guard against cases like this.

The problem with `os.chdir` is that it changes the working directory for the rest of the program, so you'd have to `chdir` back to where you were previously after running the `git rev-parse HEAD` command. This is because aliBuild expects e.g. recipes to be in a particular place relative to the directory it was started in (which it expects to be the cwd).

**Comment by adriansev** [comment]
@TimoWilken Hi! no alias but i do have these:
```
shopt -p | grep cd
shopt -s autocd
shopt -u cdable_vars
shopt -s cdspell
```
and yes, your diff seems to work, thanks a lot!!

**Comment by ktf** [comment]
@TimoWilken how about `GIT_DIR=%s/.git git rev-parse HEAD`?

**Comment by ktf** [comment]
https://github.com/alisw/alibuild/pull/742
