### ISSUE TITLE
env not propagated in recipes or wrong docummentation

### ISSUE THREAD

**Issue by jan-busa** [alisw/alibuild#745]
System used CentOS 7.9.2009, aliBuild version v1.9.8 installed from repo alice-system-deps

I was trying to set some environment variables inside recipe as instructed by [alibuild manual](https://alisw.github.io/alibuild/reference.html). It seems, that only variables set in "defaults" recipe were propagated, not ones inside "regular" one. If it is expected behavior then documentation should state this explicitly.

You can try this with attached files (rename them to .sh) and command ```aliBuild build VARIABLES --debug --defaults minimal```.
Variable FFTW3_QUAD should be set to ON but it is not.

[defaults-minimal.sh.txt](https://github.com/alisw/alibuild/files/8030840/defaults-minimal.sh.txt)
[variables.sh.txt](https://github.com/alisw/alibuild/files/8030841/variables.sh.txt)

Also as a side note, I understand from manual that if I use command line option ```--defaults minimal``` then the file defaults-minimal.sh will be used to load configuration defaults. What I don't understand is, why aliBuild still requires file defaults-release.sh to be present. Is it so, that it takes some configuration from it or it is a bug that should be reported? I would prefer not to keep defaults-release.sh, in that way I can force user to wittingly choose proper defaults file.

**Comment by TimoWilken** [comment]
I think the documentation is incomplete here -- the `env:` key isn't for variables to be set when the recipe is run, but when later recipes are run. This is so that you can e.g. change `$PATH` to include the build products of the current recipe.

So, for your example, if you had the same recipe `variables.sh` as you uploaded, and added another recipe, e.g. `other.sh`, where `other.sh` has `requires: [VARIABLES]`, then the `FFTW3_*` vars would be set in `other.sh`, but not in `variables.sh`.

If you need to set environment variables only in one recipe, use `export VAR=value` in the recipe body instead.

**Comment by ktf** [comment]
Correct. I updated  the documentation in https://github.com/alisw/alibuild/pull/746
